platform :ios, '10.0'

target 'LayoutInspectorExample' do
  use_frameworks!
	pod 'LayoutInspector', :path => '../'


  target 'LayoutInspectorExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
