platform :ios, '10.0'

target 'LayoutInspectorExample' do
    pod 'LayoutInspector', :path => '../'
    
    
    target 'LayoutInspectorExampleTests' do
        inherit! :search_paths
    end
    
    target 'LayoutInspectorExampleUITests' do
        inherit! :search_paths
    end
    
end


